title: Windows Security Guide
description: A guide to Windows security for competitions and more!
theme: just-the-docs

url: https://savvydolphin77.github.io/windows-security-guide

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
